//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopDongHo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DongHo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DongHo()
        {
            this.DatHang_ChiTiet = new HashSet<DatHang_ChiTiet>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ThuongHieu_ID { get; set; }
        public Nullable<int> TenLoai_ID { get; set; }
        public Nullable<int> ChatLieu_ID { get; set; }
        public Nullable<int> XuatXu_ID { get; set; }
        public string TenDongHo { get; set; }
        public string MauSac { get; set; }
        public Nullable<int> HanBaoHanh { get; set; }
        public Nullable<int> DonGia { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public string HinhAnhDH { get; set; }
        public string MoTa { get; set; }
    
        public virtual ChatLieu ChatLieu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DatHang_ChiTiet> DatHang_ChiTiet { get; set; }
        public virtual LoaiDH LoaiDH { get; set; }
        public virtual ThuongHieu ThuongHieu { get; set; }
        public virtual XuatXu XuatXu { get; set; }
        
        public virtual ICollection<ListDatHangTong> ListDangHangTong { get; set; }

    }
}
